/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projetoframe;

import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author vitor
 */
public class NewJFrame extends javax.swing.JFrame {
    int idade;
    public NewJFrame() {
        initComponents();
        lblResp.setVisible(false);
        txtResp.setVisible(false);
        lblResp1.setVisible(false);
        lblNresp.setVisible(false);
        panDados.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panCadastro = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblResp = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        radEletro = new javax.swing.JRadioButton();
        radTI = new javax.swing.JRadioButton();
        txtNome = new javax.swing.JTextField();
        txtResp = new javax.swing.JTextField();
        txtData = new javax.swing.JFormattedTextField();
        btnCadastro = new javax.swing.JButton();
        panDados = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblResp1 = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblNresp = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblcurso = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panCadastro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setText("NOME:");
        panCadastro.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 30, 59, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setText("DATA DE NASCIMENTO:");
        panCadastro.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 76, -1, -1));

        lblResp.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblResp.setText("NOME DO RESPONSAVEL:");
        panCadastro.add(lblResp, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 118, 179, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SELECIONE SEU CURSO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 14))); // NOI18N

        buttonGroup1.add(radEletro);
        radEletro.setText("ELETROTÉCNICA");

        buttonGroup1.add(radTI);
        radTI.setText("INFORMATICA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(radEletro)
                .addGap(18, 18, 18)
                .addComponent(radTI, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radEletro)
                    .addComponent(radTI))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        panCadastro.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, 90));

        txtNome.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        panCadastro.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 27, 528, -1));

        txtResp.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        panCadastro.add(txtResp, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 115, 419, -1));

        try {
            txtData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtData.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtData.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDataFocusLost(evt);
            }
        });
        txtData.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDataKeyPressed(evt);
            }
        });
        panCadastro.add(txtData, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 70, 118, -1));

        btnCadastro.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnCadastro.setText("CADASTRAR");
        btnCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroActionPerformed(evt);
            }
        });
        panCadastro.add(btnCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(481, 238, -1, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setText("NOME:");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setText("DATA DE NASCIMENTO:");

        lblResp1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblResp1.setText("NOME DO RESPONSAVEL:");

        lblNome.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        lblNresp.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        lblData.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel8.setText("CURSO:");

        lblcurso.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        btnVoltar.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnVoltar.setText("VOLTAR");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panDadosLayout = new javax.swing.GroupLayout(panDados);
        panDados.setLayout(panDadosLayout);
        panDadosLayout.setHorizontalGroup(
            panDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDadosLayout.createSequentialGroup()
                .addGroup(panDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panDadosLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panDadosLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(panDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panDadosLayout.createSequentialGroup()
                                .addComponent(lblResp1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblNresp, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panDadosLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(lblData, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panDadosLayout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblcurso, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(42, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panDadosLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnVoltar)
                .addGap(94, 94, 94))
        );
        panDadosLayout.setVerticalGroup(
            panDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDadosLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(panDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblResp1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNresp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(lblData, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panDadosLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel8))
                    .addGroup(panDadosLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblcurso, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVoltar)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(panDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(panDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroActionPerformed
        // PEGAR OS DADOS INSERIDOS NO PAINEL DE CADASTRO 
        String nome = txtNome.getText();
        String resp = txtResp.getText();
        String date = txtData.getText();
        // SÓ VAI CADASTRAR SE TODOS OS CAMPOS ESTIVEREM PREENCHIDOS
        System.out.println(idade);
        if ((nome.isEmpty()) || (resp.isEmpty() && idade < 18) || (date.isEmpty())) {
            JOptionPane.showMessageDialog(null, "CAMPO OBRIGATÓRIO");
        } else {
            lblNome.setText(nome);
            lblNresp.setText(resp);
            lblData.setText(date);
            //EXIBIR A SELEÇÃO DO CURSO
            String curso;
            if (radEletro.isSelected()) {
                curso = radEletro.getText();
                lblcurso.setText(curso);

            }
            if (radTI.isSelected()) {
                curso = radTI.getText();
                lblcurso.setText(curso);
            }
            // CONFERIR SE TODOS OS DADOS FORAM INSERIDOS

            // ALTERAR A VISIBILIDADE BOTÃO VOLTAR E DOS PAINÉIS 
            panCadastro.setVisible(false);
            panDados.setVisible(true);
            btnVoltar.setVisible(true);
        }

        
    }//GEN-LAST:event_btnCadastroActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // ALTERAR A VISIBILIDADE DOS PAINÉIS
        panCadastro.setVisible(true);
        panDados.setVisible(false);

        // LIMPAR O PAINEL DE CADASTRO
        txtNome.setText(" ");
        txtResp.setText(" ");
        txtData.setValue(null);
        buttonGroup1.clearSelection();

        lblResp.setVisible(false);
        txtResp.setVisible(false);
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void txtDataKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDataKeyPressed
        /*
        System.out.println("teste");// FORMATAR DATA 
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            Date dataNascimento = null;
            SimpleDateFormat formatodata = new SimpleDateFormat("dd/MM/yyyy");
            formatodata.setLenient(false);
            String date = (txtData.getText());
            try {
                dataNascimento = formatodata.parse(date);
                System.out.println(dataNascimento);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "DATA INVALIDA");
            }
            // CALCULAR IDADE DO USUARIO
            Calendar dataNasc = Calendar.getInstance();
            dataNasc.setTime(dataNascimento);

            Calendar hoje = Calendar.getInstance();
            hoje.getTime();

             idade = hoje.get(Calendar.YEAR) - dataNasc.get(Calendar.YEAR);

            dataNasc.add(Calendar.YEAR, idade);

            if (hoje.before(dataNasc)) {
                idade--;
            }
            if (idade < 18) {
                lblResp.setVisible(true);
                txtResp.setVisible(true);
                txtResp.requestFocus();
            } else {
                lblResp.setVisible(false);
                txtResp.setVisible(false);
                radEletro.requestFocus();
                radEletro.setSelected(true);
            }
        } */
    }//GEN-LAST:event_txtDataKeyPressed

    private void txtDataFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDataFocusLost
        // TORNA VISSIVEL O CAMPO DO RESPONSAVEL CASO O USUARIO SEJA DE MENOR
Date dataNascimento = null;
            SimpleDateFormat formatodata = new SimpleDateFormat("dd/MM/yyyy");
            formatodata.setLenient(false);
            String date = (txtData.getText());
            try {
                dataNascimento = formatodata.parse(date);
                System.out.println(dataNascimento);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "DATA INVALIDA");
            }
            // CALCULAR IDADE DO USUARIO
            Calendar dataNasc = Calendar.getInstance();
            dataNasc.setTime(dataNascimento);

            Calendar hoje = Calendar.getInstance();
            hoje.getTime();

             idade = hoje.get(Calendar.YEAR) - dataNasc.get(Calendar.YEAR);

            dataNasc.add(Calendar.YEAR, idade);

            if (hoje.before(dataNasc)) {
                idade--;
            }
            if (idade < 18) {
                lblResp.setVisible(true);
                txtResp.setVisible(true);
                txtResp.requestFocus();
            } else {
                lblResp.setVisible(false);
                txtResp.setVisible(false);
                radEletro.requestFocus();
                radEletro.setSelected(true);
            }
    }//GEN-LAST:event_txtDataFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastro;
    private javax.swing.JButton btnVoltar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNresp;
    private javax.swing.JLabel lblResp;
    private javax.swing.JLabel lblResp1;
    private javax.swing.JLabel lblcurso;
    private javax.swing.JPanel panCadastro;
    private javax.swing.JPanel panDados;
    private javax.swing.JRadioButton radEletro;
    private javax.swing.JRadioButton radTI;
    private javax.swing.JFormattedTextField txtData;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtResp;
    // End of variables declaration//GEN-END:variables
}
